// Bundle the upstream pure-JS Draco worker as a same-origin, static worker.
// Avoids blob: workers and wasm-unsafe-eval under the site's existing CSP.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const loader = readFileSync('node_modules/three/examples/jsm/loaders/DRACOLoader.js', 'utf8');
const worker = loader.slice(loader.indexOf('function DRACOWorker() {'));
const body = worker.slice(worker.indexOf('{') + 1, worker.lastIndexOf('export {')).trim().replace(/}\s*$/, '');
const cleanBody = body.replace(/ \/\/ eslint-disable-line no-undef/g, '');
const decoder = readFileSync('node_modules/three/examples/jsm/libs/draco/gltf/draco_decoder.js', 'utf8');
mkdirSync('public/models', { recursive: true });
writeFileSync('public/models/draco-worker.js', '// Draco decoder (Google, Apache-2.0); DRACOWorker (Three.js, MIT). Generated by scripts/hero-authoring/build-decoder.mjs.\n' + decoder + '\n' + cleanBody);
